import { keyMirror } from "@/src/utils/keymirror";

const actions = {
  ALL_ORG_GET: null,
  ALL_ORG_GET_SUCCESS: null,
  ALL_ORG_GET_ERROR: null,
  ALL_ORG_GET_CLEAR: null,

  SINGLE_ORG_GET: null,
  SINGLE_ORG_GET_SUCCESS: null,
  SINGLE_ORG_GET_ERROR: null,
  SINGLE_ORG_GET_CLEAR: null,

  ENABLE_DISABLE_ORG: null,
  ENABLE_DISABLE_ORG_SUCCESS: null,
  ENABLE_DISABLE_ORG_ERROR: null,
  ENABLE_DISABLE_ORG_CLAER: null,

  APPROVE_DENY_ORG: null,
  APPROVE_DENY_ORG_SUCCESS: null,
  APPROVE_DENY_ORG_ERROR: null,
  APPROVE_DENY_ORG_CLEAR: null,

  USER_LIST: null,
  USER_LIST_SUCCESS: null,
  USER_LIST_ERROR: null,
  USER_LIST_CLEAR: null,

  ADD_USER: null,
  ADD_USER_SUCCESS: null,
  ADD_USER_ERROR: null,
  ADD_USER_CLEAR: null,

  BY_ROLE: null,
  BY_ROLE_SUCCESS: null,
  BY_ROLE_ERROR: null,
  BY_ROLE_CLEAR: null,

  GENERATE_KEY: null,
  GENERATE_KEY_SUCCESS: null,
  GENERATE_KEY_ERROR: null,
  GENERATE_KEY_CLEAR: null,

  GET_PRODUCT: null,
  GET_PRODUCT_SUCCESS: null,
  GET_PRODUCT_ERROR: null,
  GET_PRODUCT_CLEAR: null,

  VERIFY_KEY: null,
  VERIFY_KEY_SUCCESS: null,
  VERIFY_KEY_ERROR: null,
  VERIFY_KEY_CLEAR: null,

  ADD_PRODUCT: null,
  ADD_PRODUCT_SUCCESS: null,
  ADD_PRODUCT_ERROR: null,
  ADD_PRODUCT_CLEAR: null,

  ENABLE_DISABLE_PRODUCT_OWNER: null,
  ENABLE_DISABLE_PRODUCT_OWNER_SUCCESS: null,
  ENABLE_DISABLE_PRODUCT_OWNER_ERROR: null,
  ENABLE_DISABLE_PRODUCT_OWNER_CLEAR: null,

  DEPENDENT_PRODUCT: null,
  DEPENDENT_PRODUCT_SUCCESS: null,
  DEPENDENT_PRODUCT_ERROR: null,
  DEPENDENT_PRODUCT_CLEAR: null,

  UPDATE_PRODUCT: null,
  UPDATE_PRODUCT_SUCCESS: null,
  UPDATE_PRODUCT_ERROR: null,
  UPDATE_PRODUCT_CLEAR: null,

  UPDATE_USER: null,
  UPDATE_USER_SUCCESS: null,
  UPDATE_USER_ERROR: null,
  UPDATE_USER_CLEAR: null,

  UPDATE_PAYMENT_GATEWAY_CUT: null,
  UPDATE_PAYMENT_GATEWAY_CUT_SUCCESS: null,
  UPDATE_PAYMENT_GATEWAY_CUT_ERROR: null,
  UPDATE_PAYMENT_GATEWAY_CUT_CLEAR: null,

  UPDATE_THERSHOLD: null,
  UPDATE_THERSHOLD_SUCCESS: null,
  UPDATE_THERSHOLD_ERROR: null,
  UPDATE_THERSHOLD_CLEAR: null,

  GET_PAYMENT_CHARGE: null,
  GET_PAYMENT_CHARGE_SUCCESS: null,
  GET_PAYMENT_CHARGE_ERROR: null,
  GET_PAYMENT_CHARGE_CLEAR: null,

  GET_PAYMENT_PROVIDERS_REPORTS: null,
  GET_PAYMENT_PROVIDERS_REPORTS_SUCCESS: null,
  GET_PAYMENT_PROVIDERS_REPORTS_ERROR: null,
  GET_PAYMENT_PROVIDERS_REPORTS_CLEAR: null,

  UPDATE_PAYMENT_PROVIDERS: null,
  UPDATE_PAYMENT_PROVIDERS_SUCCESS: null,
  UPDATE_PAYMENT_PROVIDERS_ERROR: null,
  UPDATE_PAYMENT_PROVIDERS_CLEAR: null,

  FETCH_PAYMENT_PROVIDERS: null,
  FETCH_PAYMENT_PROVIDERS_SUCCESS: null,
  FETCH_PAYMENT_PROVIDERS_ERROR: null,
  FETCH_PAYMENT_PROVIDERS_CLEAR: null,

  FETCH_PREFRENCE_LIST: null,
  FETCH_PREFRENCE_LIST_SUCCESS: null,
  FETCH_PREFRENCE_LIST_ERROR: null,
  FETCH_PREFRENCE_LIST_CLEAR: null,

  VERIFICATION_REPORT: null,
  VERIFICATION_REPORT_SUCCESS: null,
  VERIFICATION_REPORT_ERROR: null,
  VERIFICATION_REPORT_CLEAR: null,

  FETCH_KYC_PREFRENCE_PROVIDERS: null,
  FETCH_KYC_PREFRENCE_PROVIDERS_SUCCESS: null,
  FETCH_KYC_PREFRENCE_PROVIDERS_ERROR: null,
  FETCH_KYC_PREFRENCE_PROVIDERS_CLEAR: null,

  GET_KYC_PREFRENCE: null,
  GET_KYC_PREFRENCE_SUCCESS: null,
  GET_KYC_PREFRENCE_ERROR: null,
  GET_KYC_PREFRENCE_CLEAR: null,

  UPDATE_KYC_PREFRENCE: null,
  UPDATE_KYC_PREFRENCE_SUCCESS: null,
  UPDATE_KYC_PREFRENCE_ERROR: null,
  UPDATE_KYC_PREFRENCE_CLEAR: null,

  GET_WEBHOOK_URL: null,
  GET_WEBHOOK_URL_SUCCESS: null,
  GET_WEBHOOK_URL_ERROR: null,
  GET_WEBHOOK_URL_CLEAR: null,

  CREATE_WEBHOOK_URL: null,
  CREATE_WEBHOOK_URL_SUCCESS: null,
  CREATE_WEBHOOK_URL_ERROR: null,
  CREATE_WEBHOOK_URL_CLEAR: null,

  GET_SALES_HEADER: null,
  GET_SALES_HEADER_SUCCESS: null,
  GET_SALES_HEADER_ERROR: null,
  GET_SALES_HEADER_CLEAR: null,
};

export default keyMirror(actions);
