import { keyMirror } from "@/src/utils/keymirror";

const actions = {
  PAYMENT_REPORT: null,
  PAYMENT_REPORT_SUCCESS: null,
  PAYMENT_REPORT_ERROR: null,
  PAYMENT_REPORT_CLEAR: null,

  AUDIT_REPORT: null,
  AUDIT_REPORT_SUCCESS: null,
  AUDIT_REPORT_ERROR: null,
  AUDIT_REPORT_CLEAR: null,

  SETTLEMENT_REPORT: null,
  SETTLEMENT_REPORT_SUCCESS: null,
  SETTLEMENT_REPORT_ERROR: null,
  SETTLEMENT_REPORT_CLEAR: null,

  GET_CUSTOMER_LIST: null,
  GET_CUSTOMER_LIST_SUCCESS: null,
  GET_CUSTOMER_LIST_ERROR: null,
  GET_CUSTOMER_LIST_CLEAR: null,

  GET_SEARCH_LIST: null,
  GET_SEARCH_LIST_SUCCESS: null,
  GET_SEARCH_LIST_ERROR: null,
  GET_SEARCH_LIST_CLEAR: null,

  GET_CLIENT_LIST: null,
  GET_CLIENT_LIST_SUCCESS: null,
  GET_CLIENT_LIST_ERROR: null,
  GET_CLIENT_LIST_CLEAR: null,

  PAYMENT_REPORT_FILTER: null,
  PAYMENT_REPORT_SUCCESS: null,
  PAYMENT_REPORT_ERROR: null,
  PAYMENT_REPORT_CLEAR: null,
};

export default keyMirror(actions);
